// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by analyze_ldpc_graph_conflicts.py
//
// LDPC Graph-Aware Fence Schedule
// Only fences when consecutive rows share variable nodes (columns)

#ifndef LDPC_GRAPH_SCHEDULE_H
#define LDPC_GRAPH_SCHEDULE_H

#include <cuda_runtime.h>

// Base Graph 1 fence schedule
// BG1: 44 fences out of 45 possible
// Savings: 2.2%
template<int Z>
__device__ __forceinline__ bool needs_fence_after_row_bg1(int row) {
    switch(row) {
        case 44:
            return false;
        default:
            return true;
    }
}

// BG2: 41 fences out of 41 possible
// Savings: 0.0%
template<int Z>
__device__ __forceinline__ bool needs_fence_after_row_bg2(int row) {
    switch(row) {
            return false;
        default:
            return true;
    }
}

// Generic dispatcher based on base graph
template<int BG, int Z>
__device__ __forceinline__ bool needs_fence_after_row(int row) {
    if (BG == 1) {
        return needs_fence_after_row_bg1<Z>(row);
    } else {
        return needs_fence_after_row_bg2<Z>(row);
    }
}

#endif // LDPC_GRAPH_SCHEDULE_H
